### ISSUE TITLE
latest version

### ISSUE THREAD

**Issue by seadba** [cybertec-postgresql/zheap#1]
there is a reference to a recent tar for zheap (may 27,2021)  in the post  https://www.cybertec-postgresql.com/en/postgresql-zheap-current-status/  where would i find that?  thanks

**Comment by LorenzHenk** [comment]
We've included the link and a short installation guide in the blog post.
You can find it here: https://www.cybertec-postgresql.com/en/postgresql-zheap-current-status/#try-it-out
